// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSnKb0Ix1_TLU1GKH5ZmwlbDP-DhtbG14',
    appId: '1:1055038615919:web:05c130d6d40a3601ba789a',
    messagingSenderId: '1055038615919',
    projectId: 'todo-tracker-project-a3af0',
    authDomain: 'todo-tracker-project-a3af0.firebaseapp.com',
    storageBucket: 'todo-tracker-project-a3af0.firebasestorage.app',
    measurementId: 'G-7R2L4G275C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCedR-V1L29NTl5ww0rykTa35hA6vYXkUk',
    appId: '1:1055038615919:android:665f1c7ae40e2704ba789a',
    messagingSenderId: '1055038615919',
    projectId: 'todo-tracker-project-a3af0',
    storageBucket: 'todo-tracker-project-a3af0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy5gZ6nJzx7D7lh3p5gIcyGvC10Y5RHpo',
    appId: '1:1055038615919:ios:1ae6fcd459e3ab0fba789a',
    messagingSenderId: '1055038615919',
    projectId: 'todo-tracker-project-a3af0',
    storageBucket: 'todo-tracker-project-a3af0.firebasestorage.app',
    iosClientId: '1055038615919-e2dbgrs5d9jcs1sgns1k619pd2f7nu7t.apps.googleusercontent.com',
    iosBundleId: 'com.kthdd.todoTrackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAy5gZ6nJzx7D7lh3p5gIcyGvC10Y5RHpo',
    appId: '1:1055038615919:ios:1ae6fcd459e3ab0fba789a',
    messagingSenderId: '1055038615919',
    projectId: 'todo-tracker-project-a3af0',
    storageBucket: 'todo-tracker-project-a3af0.firebasestorage.app',
    iosClientId: '1055038615919-e2dbgrs5d9jcs1sgns1k619pd2f7nu7t.apps.googleusercontent.com',
    iosBundleId: 'com.kthdd.todoTrackerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSnKb0Ix1_TLU1GKH5ZmwlbDP-DhtbG14',
    appId: '1:1055038615919:web:08e010758ace6be0ba789a',
    messagingSenderId: '1055038615919',
    projectId: 'todo-tracker-project-a3af0',
    authDomain: 'todo-tracker-project-a3af0.firebaseapp.com',
    storageBucket: 'todo-tracker-project-a3af0.firebasestorage.app',
    measurementId: 'G-S85R7B4DJE',
  );
}
